name: Publish to PyPI

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Cache Poetry Installation
      uses: actions/cache@v1
      with:
        path: /home/runner/.cache/pypoetry/virtualenvs
        key: pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    # - name: Test With Tox
    #   run: |
    #     poetry run tox
    - name: Build with Poetry
      run: |
        poetry build
    - name: Publish to PyPI with Poetry
      env:
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish --username "$PYPI_USERNAME" --password "$PYPI_PASSWORD"
